// src/constants/routes.js (or src/constants/api-routes.js)
export const ROUTES = {
    ACCOUNTS: {
        GET_ALL: '/Accounts',
        CREATE: '/Accounts',
        GET_BY_ID: (id) => `/Accounts/${id}`,
        UPDATE: (id) => `/Accounts/${id}`,
        GET_COMMENTS: (id) => `/Accounts/${id}/comment-history`,
        ADD_COMMENT: '/Accounts/add-comments',
        DELETE: (id) => `/Accounts/archive/${id}`,
        GET_FOR_TABLE_LIST: '/Accounts/list',
        GET_ALL_CONTACTS: '/Accounts/contacts',
        GET_CONTACTS_BY_ACCOUNT: (accountId) => `/Accounts/${accountId}/contacts`,
        // Email Recipients
        GET_EMAIL_RECIPIENT_BY_ACCOUNT: (accountId) => `/Accounts/${accountId}/email-recipients`,
        GET_NOTIFICATION_SETUP_BY_ACCOUNT: (accountId) => `/Accounts/${accountId}/notification/setup`,
        SAVE_NOTIFICATION_SETUP: '/Accounts/notification-configuration',
    },
    APPLICANTS: {
        CREATE: '/Applicant',
        UPDATE: (id) => `/Applicant/${id}`,
        GET_ALL: '/Applicant',
        GET_ALL_INCLUDING_HISTORICAL: '/Applicant/All',
        GET_BY_ID: (id) => `/Applicant/${id}`,
        DELETE_DOCUMENT: () => `/Applicant/remove-document`,
        CREATE_COMMENT: (id) => `/Applicant/${id}/add-comment`,
        GET_COMMENTS_BY_APPLICANT: (id) => `/Applicant/${id}/comment-history`,
        UPDATE_COMMENT: (applicantId, commentId) => `/Applicant/${applicantId}/modify-comment/${commentId}`,
        DELETE_COMMENT: (applicantId, commentId) => `/Applicant/${applicantId}/remove-comment/${commentId}`,
        EMPLOY_APPLICANT: (id) => `/Applicant/${id}/employ`,
        // Applicant Scheds
        GET_SCHEDULES: '/Applicant/schedules',
        GET_SCHEDULE_BY_ID: (applicantId) => `/Applicant/schedules/${applicantId}`,
        CREATE_SCHEDULE: '/Applicant/schedule/add',
        UPDATE_SCHEDULE: (applicantId) => `/Applicant/schedule/${applicantId}/update`,
        DELETE_SCHEDULE: (applicantId) => `/Applicant/schedule/${applicantId}/delete`,
    },
    ATTENDANCE: {
        GET_FILTERED_LIST: '/Attendance/FilteredList',
        CREATE_ATTENDANCE: '/Attendance',
        UPDATE_ATTENDANCE: '/Attendance',
        DELETE_ATTENDANCE: (id) => `/Attendance/${id}`,
        GET_ATTENDANCE_BY_ID: (id) => `/Attendance/${id}`,
        GET_ALL_AMENDMENT_REQUESTS: '/Attendance/time-amendments-requests',
        APPROVE_AMENDMENT_REQUEST: (id) => `/Attendance/time-amendments-requests/approve/${id}`,
        REJECT_AMENDMENT_REQUEST: (id) => `/Attendance/time-amendments-requests/reject/${id}`,
    },
    AUTH: {
        LOGIN: '/Auth/login',
        REFRESH_TOKEN: '/Auth/login/refresh',
    },
    CLIENTS: { // more of Client Contacts
        GET_ALL_CONTACTS: '/Client',
        GET_CONTACTS_BY_ID: (id) => `Client/${id}`,
        CREATE_CONTACT: '/Client',
        UPDATE_CONTACT: (id) => `/Client/${id}`,
        GET_BISIT_HISTORY_BY_NAME: (name) => `/Client/${encodeURIComponent(name)}/visit-history`,
        DELETE_CONTACT: (accountId, contactId) => `/Client/${accountId}/${contactId}`,
        // EMAIL_RECIPIENTS_NAME: '/Client/email-recipients', // the list/options for Name field
        // EMAIL_RECIPIENTS_NAME_BY_CLIENT: (clientId) => `/Client/${clientId}/email-recipients`, // the list/options for Name field
        // CREATE_EMAIL_RECIPIENT: '/Client/email-recipients',
        // EMAIL_RECIPIENT_BY_CLIENT: (clientId) => `/Client/${clientId}/email-recipients/setup`, // get email recipients and the checked email types
        // Visits / Meetings
        GET_VISITS: '/Client/visits',
        ADD_VISIT: '/Client/visits/add',
        UPDATE_VISIT: (visitId) => `/Client/visits/${visitId}/update`,
        DELETE_VISIT: (visitId) => `/Client/visits/${visitId}/delete`,
    },
    EMAIL: {
        // procType : send/draft/schedule-send
        // bulletinType: Client/Staff
        GET_ALL_BULLETINS: '/Email/bulletin',
        GET_BULLETIN_BY_ID: (id) => `/Email/bulletin/${id}`,
        GET_BULLETIN_BY_TYPE: (bulletinType) => `/Email/bulletin/${bulletinType}`,
        CREATE_BULLETIN: (procType) => `/Email/bulletin/${procType}`,
        UPDATE_BULLETIN: (id, procType) => `/Email/bulletin/${id}/${procType}`,
    },
    EMAIL_SUBSCRIPTIONS: {
        GET_ALL: '/Sub/emailsubscription',
        GET_BY_ID: (id) => `/Sub/emailsubscription/${id}`,
        CREATE: '/Sub/emailsubscription/add',
        UPDATE: '/Sub/emailsubscription/update',
        DELETE: (id) => `/Sub/emailsubscription/${id}`,
    },
    EMPLOYEE: {
        GET_AS_OPTIONS: '/Employee',
        GET_ALL: '/Employee/list',
        GET_BY_ID: (id) => `/Employee/${id}`,
        // Details
        GET_DETAILS_BY_ID: (id) => `/Employee/${id}/details`,
        UPDATE_DETAILS: (id) => `/Employee/${id}/details/update`,
        UNDO_HIRE: (empNo) => `/Employee/${empNo}/undo-hire`,
        // Address
        GET_ADDRESSES: (id) => `/Employee/${id}/address`,
        ADD_ADDRESS: (id) => `/Employee/${id}/address/add`,
        UPDATE_ADDRESS: (id, addressId) => `/Employee/${id}/address/${addressId}/update`,
        DELETE_ADDRESS: (id, addressId) => `/Employee/${id}/address/${addressId}/delete`,
        // Work Schedule
        GET_WORK_SCHEDULES: (id) => `/Employee/${id}/work-schedule`,
        ADD_WORK_SCHEDULE: (id) => `/Employee/${id}/work-schedule/add`,
        UPDATE_WORK_SCHEDULE: (id, scheduleId) => `/Employee/${id}/work-schedule/${scheduleId}/update`,
        DELETE_WORK_SCHEDULE: (id, scheduleId) => `/Employee/${id}/work-schedule/${scheduleId}/delete`,
        // Attendance
        GET_ATTENDANCE: (id) => `/Employee/${id}/attendance`,
        // Leave Credits
        GET_LEAVE_CREDITS: (id) => `/Employee/${id}/leave-credits`,
        ADD_LEAVE_CREDITS: (id) => `/Employee/${id}/leave-credits/add`,
        UPDATE_LEAVE_CREDITS: (id, creditId) => `/Employee/${id}/leave-credits/${creditId}/update`,
        // Leave
        GET_LEAVE: (id) => `/Employee/${id}/leave`,
        ADD_LEAVE: (id) => `/Employee/${id}/leave/add`,
        ADD_LEAVE_UNPAID: (id) => `/Employee/${id}/leave/add/proceedUnPaid`,
        UPDATE_LEAVE: (id, leaveId) => `/Employee/${id}/leave/${leaveId}/update`,
        UPDATE_LEAVE_UNPAID: (id, leaveId) => `/Employee/${id}/leave/${leaveId}/update/proceedUnPaid`,
        DELETE_LEAVE: (id, leaveId) => `/Employee/${id}/leave/${leaveId}/delete`,
        // Salary
        GET_SALARY: (id) => `/Employee/${id}/salary`,
        ADD_SALARY: (id) => `/Employee/${id}/salary/add`,
        UPDATE_SALARY: (id, salaryId) => `/Employee/${id}/salary/${salaryId}/update`,
        GET_ALLOWANCE: (id) => `/Employee/${id}/salary/allowance`,
        ADD_ALLOWANCE: (id) => `/Employee/${id}/salary/allowance/add`,
        UPDATE_ALLOWANCE: (id, allowanceId) => `/Employee/${id}/salary/allowance/${allowanceId}/update`,
        // 13th Month
        GET_THIRTEENTH_MONTH: (id) => `/Employee/${id}/13thMonth`,
        ADD_DEBIT_13TH_MONTH: (id) => `/Employee/${id}/13thMonth/debit/add`,
        UPDATE_DEBIT_13TH_MONTH: (id, debitId) => `/Employee/${id}/13thMonth/debit/${debitId}/update`,
        DELETE_DEBIT_13TH_MONTH: (id, debitId) => `/Employee/${id}/13thMonth/debit/${debitId}/delete`,
        // Loans
        GET_LOANS: (id) => `/Employee/${id}/loans`,
        ADD_LOAN: (id) => `/Employee/${id}/loans/add`,
        UPDATE_LOAN: (id, loanId) => `/Employee/${id}/loans/${loanId}/update`,
        DELETE_LOAN: (id, loanId) => `/Employee/${id}/loans/${loanId}/delete`,
        // Documents
        GET_DOCUMENTS: (id) => `/Employee/${id}/documents`,
        ADD_DOCUMENT: (id) => `/Employee/${id}/documents/add`,
        UPDATE_DOCUMENT: (id, docId) => `/Employee/${id}/documents/${docId}/update`,
        DELETE_DOCUMENT: (id, docId) => `/Employee/${id}/documents/${docId}/delete`,
        // HR
        GET_HR_DETAILS: (id) => `/Employee/${id}/hr`,
        UPDATE_HR_DETAILS: (id) => `/Employee/${id}/hr/update`,
        // IT
        GET_IT_DETAILS: (id) => `/Employee/${id}/it`,
        UPDATE_IT_DETAILS: (id) => `/Employee/${id}/it/update`,
        // Referrals
        GET_REFERRALS: (id) => `/Employee/${id}/referrals`,
        ADD_REFERRAL: (id) => `/Employee/${id}/referrals/add`,
        UPDATE_REFERRAL: (id, referralId) => `/Employee/${id}/referrals/${referralId}/update`,
        DELETE_REFERRAL: (id, referralId) => `/Employee/${id}/referrals/${referralId}/delete`,
        // HMO
        GET_HMO_DETAILS: (id) => `/Employee/${id}/hmo`,
        UPDATE_HMO_DETAILS: (id) => `/Employee/${id}/hmo/update`,
        // Overtime
        GET_OVERTIME: (id) => `/Employee/${id}/overtime`,
        ADD_OVERTIME: (id) => `/Employee/${id}/overtime/add`,
        UPDATE_OVERTIME: (id, overtimeId) => `/Employee/${id}/overtime/${overtimeId}/update`,
        DELETE_OVERTIME: (id, overtimeId) => `/Employee/${id}/overtime/${overtimeId}/delete`,
        // DEPARTURE
        GET_DEPARTURE_DETAILS: (id) => `/Employee/${id}/departure`,
        UPDATE_DEPARTURE_DETAILS: (id) => `/Employee/${id}/departure/update`,
        // Probation Summary
        GET_PROBATIONARY_SUMMARY: (id) => `/Employee/${id}/probationary-summary`,
        UPDATE_PROBATIONARY_SUMMARY: (id) => `/Employee/${id}/probationary-summary/update`,
        // Clinic
        GET_CLINIC_COMMENTS: (id) => `/Employee/${id}/clinic/comments`,
        ADD_CLINIC_COMMENT: (id) => `/Employee/${id}/clinic/comments/add`,
        UPDATE_CLINIC_COMMENT: (id, commentId) => `/Employee/${id}/clinic/comments/${commentId}/update`,
        DELETE_COMMENT: (id, commentId) => `/Employee/${id}/clinic/comments/${commentId}/delete`,
        UPDATE_VACCINATION_DETAILS: (id) => `/Employee/${id}/clinic/vaccination-details/update`,
    },
    FILE: {
        DOWNLOAD: (path) => `/File/download?blobName=${encodeURIComponent(path)}`,
        DELETE: (path) => `/File/${encodeURIComponent(path)}`,
        UPLOAD: '/File/upload',
        GET_BY_FOLDER_PATH: (folderPath) => `/File/${encodeURIComponent(folderPath)}`,
    },
    HOLIDAY: {
        GET_ALL: '/Sub/holiday',
        GET_BY_ID: (id) => `/Sub/holiday/${id}`,
        ADD: '/Sub/holiday/add',
        UPDATE: (id) => `/Sub/holiday/${id}/update`,
        DELETE: (id) => `/Sub/holiday/${id}`,
    },
    HOME: {
        // Booking
        GET_BOOKINGS: '/Home/booking',
        GET_BOOKING_BY_ID: (id) => `/Home/booking/${id}`,
        CREATE_BOOKING: '/Home/booking/add',
        UPDATE_BOOKING: (id) => `/Home/booking/${id}/update`,
        DELETE_BOOKING: (id) => `/Home/booking/${id}/cancel`,
        // Documents
        GET_DOCUMENTS: '/Home/documents',
        ADD_DOCUMENT: '/Home/documents/add',
        UPDATE_DOCUMENT: (id) => `/Home/documents/${id}/update`,
        DELETE_DOCUMENT: (id) => `/Home/documents/${id}/delete`,
    },
    IMPORT: {
        PAYROLL_REGISTER: '/Import/payroll-register',
    },
    LATENESS_NOTIFICATIONS: {
        GET_ALL: '/Sub/latenessnotification',
        GET_BY_ID: (id) => `/Sub/latenessnotification/${id}`,
        CREATE: '/Sub/latenessnotification/add',
        UPDATE: '/Sub/latenessnotification/update',
        DELETE: (id) => `/Sub/latenessnotification/${id}`,
    },
    LISTS: {
        APPLICANT_PURPOSE: '/List/applicant-purpose',
        APPLICANT_SRC: '/List/applicant-src',
        APPLICANT_STATUS: '/List/applicant-status',
        APPLICANT_SUB_STATUS: '/List/applicant-sub-filter',
        ALL_APPLICANTS: '/List/all-applicants',
        ACTIVE_APPLICANTS: '/List/active-applicants',
        POSITIONS: '/List/positions',
        GENDER: '/List/gender',
        VACANCY_STATUS: '/List/vacancy-status',
        VACANCY_REASONS: '/List/vacancy-reasons',
        VACANCY_RECRUITER: '/List/recruiter',
        HOSTING_COST: '/List/hosting-costs',
        CLIENT_STATUS: '/List/accounts-types',
        CLIENT_TYPE: '/List/accounts-process-types',
        ACCOUNT_MANAGERS: '/List/accounts-manager',
        ACCOUNT_REFERRERS: '/List/accounts-referrer',
        COMMUNICATION_TYPE: '/List/communication-types',
        EMAIL_TYPES: '/List/email-types',
        ADDRESS_STATES: '/List/accounts-address-states',
        CONTACT_POSITIONS: '/List/client-contact-positions',
        CONTACT_COMPANIES: '/List/client-contact-companies',
        REPORTING_LINES: (accountId) => `/List/reporting-lines/${accountId}`,
        LOCATION: '/List/floors',
        RE_EMPLOYMENT_REASONS: '/List/re-employment-reasons',
        END_EMPLOYMENT_REASONS: '/List/end-employment-reasons',
        EMPLOYMENT_STATUS: '/List/employment-status',
        YES_BLANK: '/List/YesBlank',
        YES_NA_BLANK: '/List/YesNaBlank',
        YES_NO_BLANK: '/List/YesNoBlank',
        YES_NO_NA_BLANK: '/List/YesNoNaBlank',
        YES_NO_TBA: '/List/YesNoTba',
        YES_NO_TBA_BLANK: '/List/YesNoTbaBlank',
        YES_NO_MAYBE_BLANK: '/List/YesNoMaybeBlank',
        NO_YES_NA: '/List/NoYesNA',
        YES_NO_EMPTY: '/List/YesNoEmpty',
        NATURE_LIST: '/List/nature-list',
        HR_PARTNERS: '/List/hr-partners',
        LOAN_TYPE: '/List/loan-types',
        DEPARTMENT: '/List/department',
        USER_BY_DEPARTMENT: (departmentId) => `/List/active-employees/department/${departmentId}`,
        TICKET_PRIO_STATUS: '/List/ticket-prio-status',
        TICKET_STATUS: '/List/ticket-status',
        ALL_EMPLOYEES: '/List/all-employees',
        ACTIVE_EMPLOYEES: '/List/active-employees',
        DEBIT_REASONS: '/List/debit-reasons',
        WFH_SETUP: '/List/wfh-setup',
        ROOMS: '/List/rooms',
        BOOKING_ITEMS: '/List/conference-booking-item',
        GROUPS: '/List/group-list',
        PAYROLL_REGISTRY_UPLOADS: '/List/payroll-registry-uploads',
        PERMISSIONS: '/List/system-features',
        // Exists in SETTINGS.ENTITY
        DOCUMENT_TYPES: '/List/document-types',
        CIVIL_STATUS: '/List/civil-status',
        DEDUCTION_TYPES: '/List/deduction-types',
        LATENESS_REASONS: '/List/lateness-reasons',
        LEAVE_TYPES: '/List/leave-types',
        PUNCTUALITY_TYPES: '/List/punctuality-types',
        COUNTRIES: '/List/countries',
        HOLIDAY_TYPES: '/List/holiday-types',
        WEB_USER_ROLES: '/List/webusers-roles',
    },
    PERMISSIONS: {
        GET_ALL: '/Permissions',
    },
    POSITIONS: {
        GET_ALL: '/List/positions',
    },
    REPORTS: {
        // Finance
        ATTENDANCE_ND_SUMMARY: '/Reports/Excel/FinanceAndAccounting/AttendanceNDSummary',
        ATTENDANCE_SUMMARY: '/Reports/Excel/FinanceAndAccounting/AttendanceSummary',
        MEALS_AND_HOLIDAYS_SUMMARY: '/Reports/Excel/FinanceAndAccounting/MealsandHolidaysSummary',
        THIRTEENTH_MONTH_SUMMARY: '/Reports/Excel/FinanceAndAccounting/13MonthSummary',
        LATE_OVERBREAKS_SUMMARY: '/Reports/Excel/FinanceAndAccounting/LateOverbreaksSummary',
        OVERTIME_SUMMARY: '/Reports/Excel/FinanceAndAccounting/OvertimeSummary',
        SALARY_INCREASE_SUMMARY: '/Reports/Excel/FinanceAndAccounting/SalaryIncreaseSummary',
        LOANS_SUMMARY: '/Reports/Excel/FinanceAndAccounting/LoansSummary',
        LEAVES_SUMMARY: '/Reports/Excel/FinanceAndAccounting/LeavesSummary',
        // HR
        COMPLIANCE: '/Reports/Excel/HR/Compliance',
        EMPLOYEE_DETAILS: '/Reports/Excel/HR/EmployeeDetails',
        // Employee HR Docs
        COE: '/Reports/Pdf/COE',
        EXIT_INTERVIEW: (empId) => `/Reports/Pdf/ExitInterview/${empId}`,
        CLEARANCE_FORM: (empId) => `/Reports/Pdf/ClearanceForm/${empId}`,
    },
    ROLES: {
        GET_ALL: '/List/user-roles',
        GET_ACCESS_BY_ID: (id) => `/Users/role/${id}/access`,
        CREATE: '/Users/role/create',
        UPDATE: (id) => `Users/role/${id}/update`,
        DELETE: (id) => `/Users/role/${id}/delete`,
    },
    SETTINGS: {
        // Generic settings route generator
        ENTITY: (entityName, entityNamePlural) => ({
            GET_ALL: `/Sub/${entityNamePlural}`,
            CREATE: `/Sub/${entityName}/add`,
            GET_BY_ID: (id) => `/Sub/${entityNamePlural}/${id}`,
            UPDATE: `/Sub/${entityName}/update`,
            DELETE: (id) => `/Sub/${entityNamePlural}/${id}`,
        }),
        WORK_SCHED_TYPES: {
            UPDATE: (id) => `/Sub/work-schedule-types/${id}/update`,
        }
    },
    TICKETING: {
        GET_ALL: '/Ticketing',
        GET_ALL_INCLUDING_HISTORICAL: '/Ticketing/All',
        CREATE: '/Ticketing',
        GET_BY_ID: (id) => `/Ticketing/${id}/details`,
        UPDATE: (id) => `/Ticketing/${id}/update`,
        DELETE: (id) => `/Ticketing/${id}/delete`,
    },
    USERS: {
        GET_ALL: '/Users',
        CREATE: '/Users',
        GET_BY_ID: (id) => `/Users/${id}`,
        UPDATE: (id) => `/Users/${id}`,
        DELETE: (id) => `/Users/${id}`,
        UPDATE_STATUS: (id, status) => `/Users/${id}/set-user-status/${status}`,
        REQUEST_SEND_VERIFICATION: (email) => `/Users/${email}/verification-request`,
        VERIFY: (encryptedEmail) => `Users/verify/${encryptedEmail}`,
        REQUEST_RESET_PASSWORD: (encryptedEmail) => `/Users/${encryptedEmail}/reset-password-request`,
        RESET_PASSWORD: (encryptedEmail) => `/Users/reset-password/${encryptedEmail}`,
        // Web Users
        CREATE_WEB_USER: '/Users/webuser/create',
        UPDATE_WEB_USER: (id) => `/Users/webuser/${id}/update`,
        GET_WEB_USER_BY_ID: (id) => `/Users/webuser/${id}`,
        GET_ALL_WEB_USERS: '/Users/webuser',
        DELETE_WEB_USER: (id) => `/Users/webuser/${id}/delete`,
    },
    USER_REQUESTS: {
        GET_ALL: '/UserRequests',
        GET_BY_ID: (id) => `/UserRequests/${id}`,
        CREATE: '/UserRequests',
        UPDATE: (id) => `/UserRequests/${id}`,
        DELETE: (id) => `/UserRequests/${id}`,
    },
    VACANT_POSITIONS: {
        GET_ALL: '/Vacancy',
        CREATE: '/Vacancy',
        GET_BY_ID: (id) => `/Vacancy/${id}`,
        UPDATE: (id) => `/Vacancy/${id}`,
        DELETE: (id) => `/Vacancy/${id}`,
    },
}